### PR TITLE
Fixed outdated phpseclib namespaces

### PR DESCRIPTION
**Pull request by drpayyne**
#### FIXED

- invalid namespace `\phpseclib\` by reusing already imported `\phpseclib3\` namespace

### CODE REVIEW

**Review by ihor-sviziev — APPROVED** [review]

**Comment by ihor-sviziev** [comment]
@terrafrost, could you check the changes from this PR?

**Comment by drpayyne** [comment]
Wow @ihor-sviziev, didn't expect to see a fellow Magento member here. :) nice!

**Comment by ihor-sviziev** [comment]
@drpayyne, basically, that' because of your PR https://github.com/magento/magento2/pull/33363 :)

**Review by Den4ik — APPROVED** [review]

**Comment by terrafrost** [comment]
I cherry-picked this to 1.0 and merged to 2.0 and master:

https://github.com/phpseclib/mcrypt_compat/commit/702d30bce6e2296303ecc4d3d71025abc980bfa1

Thanks!

**Pull request closed without merging**
